version: 1.0.0
workflows:
  android-gusto-build:
    name: Gusto Android Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    
    environment:
      groups:
        - android-signing
      vars:
        ANDROID_NDK_VERSION: "25.2.9519653"
      java: 17
      flutter: 3.44.8

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Установка и активация Python 3.13
        script: |
          pyenv install 3.13.0 --skip-existing
          pyenv global 3.13.0
          echo 'export PATH="$HOME/.pyenv/shims:$PATH"' >> $CM_ENV
          
      - name: Install dependencies
        script: |
          python -m pip install --upgrade pip
          pip install setuptools flet requests
          
      - name: Настройка Android SDK окружения
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION" >> local.properties

      - name: Build APK
        script: |
          cd src
          # Используем синтаксис как в вашем примере шаблона
          yes | flet build apk --product "Gusto"

    artifacts:
      - src/build/**/*.apk

    publishing:
      email:
        recipients:
          - profardog@gmail.com
        notify:
          success: true
          failure: true
